name: olive_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  icons_launcher: ^3.0.0
  lordicon: ^1.0.3
  path_provider: ^2.1.2
  sembast: ^3.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

icons_launcher:
  image_path: "assets/launcher_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true


flutter_native_splash:
  fullscreen: true

  # Use background IMAGE instead of color (required for gradient)
  color: "#363C44"

  # Center logo
  image: assets/splash_logo.png

  # Image alignment
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

  # --------------------
  # ANDROID 12+
  # --------------------
  android_12:
    # Android 12 does NOT support gradient backgrounds
    # Use a neutral color close to your design
    color: "#363C44"

    # Center logo (will be clipped into a circle)
    image: assets/splash_logo.png




flutter:
  uses-material-design: true

#Assets
  assets:
    - assets/avatar.json
    - assets/inbox.json
    - assets/message.json
    - assets/shopping-bag.json
    - assets/notification.json
    - assets/settings.json
    - assets/default_avatar.png
    - assets/product_cover.png
    - assets/customer_cover.png
    - assets/launcher_icon.png
    - assets/splash_logo.png
