name: olive_app
description: "Apcommerz"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  app_links: ^6.4.1
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_slidable: ^4.0.3
  intl: ^0.20.2
  lordicon: ^1.0.3
  lucide_icons_flutter: ^3.1.9
  marquee: ^2.3.0
  path_provider: ^2.1.2
  sembast: ^3.8.6
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

#Assets
  assets:
    - assets/avatar.json
    - assets/inbox.json
    - assets/message.json
    - assets/shopping-bag.json
    - assets/notification.json
    - assets/cloud-download-failed.json
    - assets/network_error.png
    - assets/settings.json
    - assets/default_avatar.png
    - assets/product_cover.png
    - assets/customer_cover.png
    - assets/no_customer.png
    - assets/google.png
    - assets/github.png
    - assets/banner_image_1.png
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-VariableFont_wght.ttf
        - asset: assets/fonts/RobotoCondensed-Italic-VariableFont_wght.ttf
          style: italic

